# Generated by Django 3.1b1 on 2020-07-20 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materijal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=300)),
                ('sifra', models.CharField(max_length=50)),
                ('mjerna_jedinica', models.CharField(max_length=10)),
                ('skladiste_kolicina', models.IntegerField(default=0)),
                ('cijena', models.FloatField()),
                ('vrijednost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Racuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=150)),
                ('ulaz_izlaz', models.CharField(max_length=10)),
                ('broj_racuna', models.CharField(max_length=50)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Krm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('datum_kolicina_skladiste', models.IntegerField()),
                ('vrijednost', models.FloatField()),
                ('materijalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krm.materijal')),
                ('racunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krm.racuni')),
            ],
        ),
    ]
