# Generated by Django 3.1b1 on 2020-07-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='krm',
            table='Krm',
        ),
        migrations.AlterModelTable(
            name='materijal',
            table='Materijal',
        ),
        migrations.AlterModelTable(
            name='racuni',
            table='Racuni',
        ),
    ]
