# Generated by Django 3.1b1 on 2020-07-20 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krm', '0002_auto_20200721_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krm',
            name='materijalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krm.materijal', verbose_name='materijalID'),
        ),
        migrations.AlterField(
            model_name='krm',
            name='racunID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krm.racuni', verbose_name='racunID'),
        ),
    ]
