# Generated by Django 3.1b1 on 2020-07-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krm', '0004_auto_20200721_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krm',
            name='materijalID',
            field=models.ForeignKey(db_column='materijalID', on_delete=django.db.models.deletion.CASCADE, to='krm.materijal'),
        ),
        migrations.AlterField(
            model_name='krm',
            name='racunID',
            field=models.ForeignKey(db_column='racunID', on_delete=django.db.models.deletion.CASCADE, to='krm.racuni'),
        ),
    ]
