# Generated by Django 3.1b1 on 2020-07-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krm', '0005_auto_20200721_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krm',
            name='datum_kolicina_skladiste',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='skladiste_kolicina',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
